#!/bin/bash
#Purpose: down 2020 DailyImmigPort data.
#Create-Date: 2023-05-24

# Text color setting
NC="\033[0m" # Color reset
BLACK="\033[0;30m"
RED="\033[0;31m"
GREEN="\033[0;32m"
YELLOW="\033[0;33m"
BLUE="\033[0;34m"
PURPLE="\033[0;35m"
CYAN="\033[0;36m"
WHITE="\033[0;37m"

dataset_list_2018="
https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=16598CA4-B527-4DCA-AE99-9E1572338F3F
https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=CCA938C8-4902-4CD6-9EFD-FBF633879C90
https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=6B69921F-A5C9-46D2-9A56-BBD8604361A7
https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=0B271D0C-A6B8-44A4-B983-523DF9020F45
https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=F2361726-A634-47AC-939F-C44A534BB0E6
https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=E4CD5326-815C-46E1-8555-474437520DD7
https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=98A3F482-13C0-4E98-ADCA-6DAC4295C20F
https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=D9A73E05-8D55-456B-A4B1-74BAA9253BE7
https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=489607A8-1FAB-4D43-AC86-44009B21BA17
https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=28534FFC-4EE6-43B2-AE7B-D634BA80DB67
https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=1D7A393D-AD04-4A3B-AD4E-F167310CBD52
https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=1CCFE6AE-AB99-44D7-B127-5A80012B60F0"

dataset_list_2019="
https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=A1E9D0CF-1B5F-441A-92CB-7B5CCB249D18
https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=41A66FA2-6108-49FC-8FE1-EE7551058F97
https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=C3349518-DF3D-4754-88B6-EADE6945B332
https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=2C67A5BB-2C43-4AA2-A5F5-AC104FC1F4E7
https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=DDB62E0A-8090-40F5-A947-CFDFF8D44A29
https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=84F15C09-08FF-466A-A04E-BA790559E69E
https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=EBD21E6E-CA0C-4E6A-8F24-76DA3CF36DBD
https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=2EB28755-475B-4987-BA86-111442F72C55
https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=0BB07C69-6D62-4276-B86F-1C59CDC71BF5
https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=3A3D2C5C-F31D-4C6E-801E-03811E24213F
https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=6C107BD4-8A16-453E-90BC-13751DBCA994
https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=7BC46E87-7774-44DC-9D64-11A5E3335739"

dataset_list_2020="
https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=EEEBDF54-B1CC-42D8-8375-ADFEE149EB2C
https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=1AF0ADAD-F262-4AF5-8F43-FB83A3448AA0
https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=8099181F-15F1-4EBF-AA57-A0B10C755615
https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=016CB666-09D4-46CD-A3AE-1BF86899E146
https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=15112836-06E1-4058-A947-5BFABFFD94A2
https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=764BA741-C68E-41DC-ACD4-78E5569CFDA1
https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=9A092C4D-7308-4003-BAD9-02D327FCA615
https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=49390CCA-4672-45CC-9586-0E8DFBEA4F3E
https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=8F45B4FC-0CD8-40F4-818E-D46E32E76D41
https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=92790B45-C4DC-4AAD-B56B-B44A02C63FFC
https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=58018F40-0223-4C59-BA9C-30EB2575091C
https://data.moi.gov.tw/MoiOD/System/DownloadFile.aspx?DATA=727BB9F6-82BA-4B9C-9F62-1099FC3A8EED"



ls ~/DailyImmigPort &> /dev/null
[ $? == 0 ] && rm -r ~/DailyImmigPort
hdfs dfs -ls final_exam/DailyImmigPort &> /dev/null
[ $? == 0 ] && hdfs dfs -rm -r final_exam/DailyImmigPort

ls ~/DailyImmigPort/{original-data,fix-data} &> /dev/null
[ $? != 0 ] && mkdir -p ~/DailyImmigPort/{original-data,fix-data}

hdfs dfs -ls final_exam &> /dev/null
[ $? != 0 ] && hdfs dfs -mkdir final_exam &> /dev/null || hdfs dfs -rm -r final_exam/DailyImmigPort &> /dev/null

hdfs dfs -ls final_exam/DailyImmigPort &> /dev/null
[ $? != 0 ] && hdfs dfs -mkdir final_exam/DailyImmigPort &> /dev/null || hdfs dfs -rm -r final_exam/DailyImmigPort/* &> /dev/null

date18="201801"
for list18 in ${dataset_list_2018}
do
  wget "${list18}" -O ~/DailyImmigPort/${date18}_DailyImmigPort.zip > /dev/null 2>&1
  [ $? == 0 ] && echo -e " [${GREEN}●${NC}] ${date18}_DailyImmigPort.zip download success." || echo -e " [${RED}●${NC}] ${date19}_DailyImmigPort.zip download failed."

  original18=$(unzip -l ~/DailyImmigPort/${date18}_DailyImmigPort.zip | grep "${date18}" | tail -n 1 | awk '{ print $4 }')
  fix18=$(unzip -l ~/DailyImmigPort/${date18}_DailyImmigPort.zip | grep "${date18}" | tail -n 1 | awk '{ print $4 }' | sed 's/.csv/_Fix.csv/g')
  unzip ~/DailyImmigPort/${date18}_DailyImmigPort.zip ${original18} -d ~/DailyImmigPort/original-data/ &> /dev/null
  [ $? == 0 ] && echo -e " [${GREEN}●${NC}] ${date18}_DailyImmigPort.zip unzip success." || echo -e " [${RED}●${NC}] ${date18}_DailyImmigPort.zip unzip failed."

  ls ~/DailyImmigPort/original-data/${original18} &> /dev/null
  [ $? == 0 ] && rm ~/DailyImmigPort/${date18}_DailyImmigPort.zip

  cat ~/DailyImmigPort/original-data/${original18} | tr -s ',,,' ',' | cut -d ',' -f 1-4,15 > ~/DailyImmigPort/fix-data/${fix18}
  sed -i '1,2d' ~/DailyImmigPort/fix-data/${fix18}

  hdfs dfs -put ~/DailyImmigPort/fix-data/${fix18} final_exam/DailyImmigPort/${fix18}
  [ $? == 0 ] && echo -e " [${GREEN}●${NC}] ${fix18} put success." || echo -e " [${RED}●${NC}] ${fix18} put failed."
  date18=$((${date18}+1))
  echo "---"
done

date19="201901"
for list19 in ${dataset_list_2019}
do
  wget "${list19}" -O ~/DailyImmigPort/${date19}_DailyImmigPort.zip > /dev/null 2>&1
  [ $? == 0 ] && echo -e " [${GREEN}●${NC}] ${date19}_DailyImmigPort.zip download success." || echo -e " [${RED}●${NC}] ${date19}_DailyImmigPort.zip download failed."

  original19=$(unzip -l ~/DailyImmigPort/${date19}_DailyImmigPort.zip | grep "${date19}" | tail -n 1 | awk '{ print $4 }')
  fix19=$(unzip -l ~/DailyImmigPort/${date19}_DailyImmigPort.zip | grep "${date19}" | tail -n 1 | awk '{ print $4 }' | sed 's/.csv/_Fix.csv/g')
  unzip ~/DailyImmigPort/${date19}_DailyImmigPort.zip ${original19} -d ~/DailyImmigPort/original-data/ &> /dev/null
  [ $? == 0 ] && echo -e " [${GREEN}●${NC}] ${date19}_DailyImmigPort.zip unzip success." || echo -e " [${RED}●${NC}] ${date19}_DailyImmigPort.zip unzip failed."

  ls ~/DailyImmigPort/original-data/${original19} &> /dev/null
  [ $? == 0 ] && rm ~/DailyImmigPort/${date19}_DailyImmigPort.zip

  cat ~/DailyImmigPort/original-data/${original19} | tr -s ',,,' ',' | cut -d ',' -f 1-4,15 > ~/DailyImmigPort/fix-data/${fix19}
  sed -i '1,2d' ~/DailyImmigPort/fix-data/${fix19}

  hdfs dfs -put ~/DailyImmigPort/fix-data/${fix19} final_exam/DailyImmigPort/${fix19}
  [ $? == 0 ] && echo -e " [${GREEN}●${NC}] ${fix19} put success." || echo -e " [${RED}●${NC}] ${fix19} put failed."
  date19=$((${date19}+1))
  echo "---"
done

#201906
rm -r DailyImmigPort/fix-data/20190630-DailyImmigPort_* &> /dev/null
hdfs dfs -rm -r final_exam/DailyImmigPort/20190630-DailyImmigPort_Fix.csv &> /dev/null
cat DailyImmigPort/original-data/20190630-DailyImmigPort.csv | cut -d ',' -f 1,2,5,8,39 > DailyImmigPort/fix-data/20190630-DailyImmigPort_fix.csv &> /dev/null
sed -i '/日期,入出境總人數_小計,桃園一期小計,桃園二期小計,松山機場小計/d' ~/DailyImmigPort/fix-data/20190630-DailyImmigPort_Fix.csv &> /dev/null
hdfs dfs -put ~/DailyImmigPort/fix-data/20190630-DailyImmigPort_Fix.csv final_exam/DailyImmigPort/20190630-DailyImmigPort_Fix.csv &> /dev/null
  
date20="202001"
for list20 in ${dataset_list_2020}
do
  wget "${list20}" -O ~/DailyImmigPort/${date20}_DailyImmigPort.zip > /dev/null 2>&1
  [ $? == 0 ] && echo -e " [${GREEN}●${NC}] ${date20}_DailyImmigPort.zip download success." || echo -e " [${RED}●${NC}] ${date20}_DailyImmigPort.zip download failed."

  original=$(unzip -l ~/DailyImmigPort/${date20}_DailyImmigPort.zip | grep "${date20}" | tail -n 1 | awk '{ print $4 }')
  fix=$(unzip -l ~/DailyImmigPort/${date20}_DailyImmigPort.zip | grep "${date20}" | tail -n 1 | awk '{ print $4 }' | sed 's/.csv/_Fix.csv/g')
  unzip ~/DailyImmigPort/${date20}_DailyImmigPort.zip ${original} -d ~/DailyImmigPort/original-data/ &> /dev/null
  [ $? == 0 ] && echo -e " [${GREEN}●${NC}] ${date20}_DailyImmigPort.zip unzip success." || echo -e " [${RED}●${NC}] ${date20}_DailyImmigPort.zip unzip failed."

  ls ~/DailyImmigPort/original-data/${original} &> /dev/null
  [ $? == 0 ] && rm ~/DailyImmigPort/${date20}_DailyImmigPort.zip

  cat ~/DailyImmigPort/original-data/${original} | cut -d ',' -f 1,2,5,8,39 > ~/DailyImmigPort/fix-data/${fix}
  sed -i '/日期,入出境總人數_小計,桃園一期小計,桃園二期小計,松山機場小計/d' ~/DailyImmigPort/fix-data/${fix}

  hdfs dfs -put ~/DailyImmigPort/fix-data/${fix} final_exam/DailyImmigPort/${fix}
  [ $? == 0 ] && echo -e " [${GREEN}●${NC}] ${fix} put success." || echo -e " [${RED}●${NC}] ${fix} put failed."
  date20=$((${date20}+1))
  echo "---"
done
